# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170918_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_nsfw',
            field=models.BooleanField(default=False, verbose_name='NSFW?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='spoiler?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=wiki.models.WikiSlugField(unique=True),
        ),
    ]
