# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20170919_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', wiki.models.WikiSlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='wiki.Tag'),
        ),
    ]
