# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20170922_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='', help_text='Formatted using Markdown', verbose_name='tag description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', related_query_name='article', to='wiki.Tag'),
        ),
    ]
