# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20170922_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='page title')),
                ('slug', wiki.models.WikiSlugField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=wiki.models.WikiSlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Formatted using Markdown', verbose_name='tag description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=wiki.models.WikiSlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirectpages', related_query_name='redirectpage', to='wiki.Article'),
        ),
    ]
