# Generated by Django 3.0 on 2019-12-06 23:49

from django.conf import settings
from django.db import migrations


def create_special_pages(apps, schema_editor):
    Article = apps.get_model('wiki', 'Article')

    try:
        title = settings.WIKI['title']
    except (AttributeError,KeyError):
        title = 'Welcom to WorldWiki!'

    Article.objects.get_or_create(
        slug='special:start',
        defaults={
            'title': title,
            'is_published': True,
            'markdown': 'Welcome to WorldWiki! Edit this page to get started creating your world!',
        },
    )
    Article.objects.get_or_create(
        slug='special:404',
        defaults={
            'title': 'Page Not Found',
            'is_published': True,
            'markdown': '''
# Oops!

It looks like you've found a page that doesn't exist! Most likely you followed a link to a page that hasn't been created yet, or else you found a stale link pointing to a page that's been deleted.

Whatever the reason, there's nothing more to see here.
'''.strip(),
        },
    )


def reverse(apps, schema_editor):
    # We may or may not have created default objects.
    # Play it safe and just do nothing.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20170925_1523'),
    ]

    operations = [
        migrations.RunPython(create_special_pages, reverse),
    ]
