# Generated by Django 3.0 on 2019-12-09 21:24

from django.db import migrations


def rename_special_pages(apps, schema_editor):
    Article = apps.get_model('wiki', 'Article')

    start = Article.objects.get(slug='special:start')
    start.slug = 'start'
    start.save()

    not_found = Article.objects.get(slug='special:404')
    not_found.slug = 'Error404'
    not_found.save()

    try:
        sidebar = Article.objects.get(slug='special:sidebar')
        sidebar.slug = 'sidebar'
        sidebar.save()
    except Article.DoesNotExist:
        pass


def reverse_special_pages(apps, schema_editor):
    Article = apps.get_model('wiki', 'Article')

    start = Article.objects.get(slug='start')
    start.slug = 'special:start'
    start.save()

    not_found = Article.objects.get(slug='Error404')
    not_found.slug = 'special:404'
    not_found.save()

    try:
        sidebar = Article.objects.get(slug='sidebar')
        sidebar.slug = 'special:sidebar'
        sidebar.save()
    except Article.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_add_special_pages'),
    ]

    operations = [
        migrations.RunPython(rename_special_pages, reverse_special_pages),
    ]
