# Generated by Django 3.0 on 2019-12-11 21:18

from django.db import migrations
import wiki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_rename_special_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('slug',)},
        ),
        migrations.AddField(
            model_name='article',
            name='namespace',
            field=wiki.fields.WikiNamespaceField(blank=True, default='', max_length=128),
        ),
    ]
