# Generated by Django 3.0 on 2019-12-12 21:44

from django.db import migrations
import wiki.slug


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20191211_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectpage',
            name='namespace',
            field=wiki.slug.WikiNamespaceField(blank=True, default='', max_length=128),
        ),
    ]
