# Generated by Django 3.0 on 2019-12-17 22:57

from django.db import migrations


def create_redirect_pages(apps, schema_editor):
    Article = apps.get_model('wiki', 'Article')
    RedirectPage = apps.get_model('wiki', 'RedirectPage')

    for redirect in RedirectPage.objects.all():
        page = Article(
            title = redirect.title,
            namespace = redirect.namespace,
            slug = redirect.slug,
            is_published = True,
        )

        md = '[[REDIRECT:/{namespace}/{slug}]]'.format(
            namespace = redirect.article.namespace,
            slug = redirect.article.slug,
        )
        page.markdown = md

        page.save()


def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_redirectpage_namespace'),
    ]

    operations = [
        migrations.RunPython(create_redirect_pages, reverse),
    ]
