# Generated by Django 3.0 on 2019-12-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_create_redirect_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedirectPage',
        ),
    ]
