# Generated by Django 3.0 on 2019-12-20 23:02

from django.db import migrations
import wiki.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_delete_redirectpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=wiki.fields.WikiSlugField(blank=True),
        ),
    ]
