# Generated by Django 3.0 on 2019-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20191220_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=250, unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'ordering': ('term',),
            },
        ),
    ]
